# Copyright 2022 The Native Link Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.4'

services:
  native_link_local_cas:
    image: trace_machina/native-link:latest
    build:
      context: ../..
      dockerfile: ./deployment-examples/docker-compose/Dockerfile
      network: host
      args:
        - ADDITIONAL_SETUP_WORKER_CMD=${ADDITIONAL_SETUP_WORKER_CMD:-}
    volumes:
      - ${NATIVE_LINK_DIR:-~/.cache/native-link}:/root/.cache/native-link
      - type: bind
        source: .
        target: /root
    environment:
      RUST_LOG: ${RUST_LOG:-warn}
    ports: [ "50051:50051/tcp", "127.0.0.1:50061:50061", "50071:50071/tcp", ]
    command: |
      native-link /root/local-storage-cas.json

  native_link_scheduler:
    image: trace_machina/native-link:latest
    build:
      context: ../..
      dockerfile: ./deployment-examples/docker-compose/Dockerfile
      network: host
      args:
        - ADDITIONAL_SETUP_WORKER_CMD=${ADDITIONAL_SETUP_WORKER_CMD:-}
    volumes:
      - type: bind
        source: .
        target: /root
    environment:
      RUST_LOG: ${RUST_LOG:-warn}
      CAS_ENDPOINT: native_link_local_cas
    ports: [ "50052:50052/tcp" ]
    command: |
      native-link /root/scheduler.json

  native_link_executor:
    image: trace_machina/native-link:latest
    build:
      context: ../..
      dockerfile: ./deployment-examples/docker-compose/Dockerfile
      network: host
      args:
        - ADDITIONAL_SETUP_WORKER_CMD=${ADDITIONAL_SETUP_WORKER_CMD:-}
    volumes:
      - ${NATIVE_LINK_DIR:-~/.cache/native-link}:/root/.cache/native-link
      - type: bind
        source: .
        target: /root
    environment:
      RUST_LOG: ${RUST_LOG:-warn}
      CAS_ENDPOINT: native_link_local_cas
      SCHEDULER_ENDPOINT: native_link_scheduler
    command: |
      native-link /root/worker.json
