[package]
name = "nativelink-state"
version = "0.4.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-util = { path = "../nativelink-util" }
nativelink-proto = { path = "../nativelink-proto" }

async-trait = "0.1.80"
tokio = { version = "1.37.0", features = ["sync", "rt", "parking_lot"] }
bitflags = "2.5.0"
futures = "0.3.30"
prost = "0.12.6"
prost-types = "0.12.6"
uuid = { version = "1.8.0", features = ["serde", "v4"] }
blake3 = { version = "1.5.1", features = ["serde"] }
hex = "0.4.3"
serde = "1.0.203"
serde_json = "1.0.117"

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }

pretty_assertions = "1.4.0"
