[package]
name = "nativelink-error"
version = "0.4.0"
edition = "2021"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[dependencies]
nativelink-proto = { path = "../nativelink-proto" }
nativelink-metric = { path = "../nativelink-metric" }

hex = "0.4.3"
prost = "0.13.1"
prost-types = "0.13.1"
redis = "0.25.4"
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.38.0" }
tonic = { version = "0.12.0", features = ["gzip"] }
