---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # Don't install the default CNI.
  disableDefaultCNI: true
  kubeProxyMode: none
nodes:
- role: control-plane
{{- range . }}
- role: worker
  extraMounts:
  {{- range .ExtraMounts }}
  - hostPath: {{ .HostPath }}
    containerPath: {{ .ContainerPath }}
    readOnly: {{ .ReadOnly }}
  {{- end }}
{{- end }}
containerdConfigPatches:
   - |-
     [plugins."io.containerd.grpc.v1.cri".registry]
        config_path = "/etc/containerd/certs.d"
