---
linters:
  enable-all: true
  disable:
    # Deprecated.
    - execinquery
    - gomnd

    # Allow all packages for now.
    - depguard

    # TODO(aaronmondal): Fix these at some point.
    - exhaustruct
