[package]
name = "nativelink-worker"
version = "0.4.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-proto = { path = "../nativelink-proto" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-store = { path = "../nativelink-store" }
nativelink-metric = { path = "../nativelink-metric" }

async-lock = "3.4.0"
bytes = "1.6.1"
filetime = "0.2.23"
formatx = "0.2.2"
futures = "0.3.30"
parking_lot = "0.12.3"
prost = "0.13.1"
relative-path = "1.9.3"
scopeguard = "1.2.0"
serde = "1.0.204"
serde_json5 = "0.1.0"
shlex = "1.3.0"
tokio = { version = "1.38.0", features = ["sync", "rt", "process"] }
tokio-stream = { version = "0.1.15", features = ["fs"] }
tonic = { version = "0.12.0", features = ["gzip", "tls"] }
tracing = "0.1.40"
uuid = { version = "1.10.0", features = ["v4"] }

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }

hyper = "1.4.1"
hyper-util = "0.1.6"
once_cell = "1.19.0"
pretty_assertions = "1.4.0"
prost-types = "0.13.1"
rand = "0.8.5"
