---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: nativelink-rebuild-tt
spec:
  params:
    - name: flakeOutput
      description: |
        The output of a Nix Flake. This output must refer to an image built with
        nix2container.

        See:
          - https://nixos.wiki/wiki/Flakes for more in formation on the Flake
            URL schema.
          - https://github.com/nlewo/nix2container for more information on the
            required builder for the flake outputs.

        Examples:
          - "/mnt/src_root#someoutput" for a flake output in the `output-src`
            directory.
          - "github:TraceMachina/nativelink#image" for the latest nativelink
            image.
          - "github:<user>/<repo>?ref=pull/<PR_NUMBER>/head#<PACKAGE>" to use
            an image from a pull request of a repository on GitHub.
    - name: imageNameOverride
      description: |
        An optional override for the image name when pushing to the registry.

        By default the tag is derived from the flake output via
        `$(nix eval /mnt/src_root#<imageoutput>.imageName --raw)` making
        invocations reproducible. This reproducibility may be broken by
        overriding the name with some arbitrary value.
      default: ""
    - name: imageTagOverride
      description: |
        An optional override for the image tag when pushing to the registry.

        By default the tag is derived from the flake output via
        `$(nix eval /mnt/src_root#<imageoutput>.imageTag --raw)` making
        invocations reproducible. This reproducibility may be broken by
        overriding this tag with some arbitrary value.

        Production deployments shouldn't make use of this value to ensure
        reproducibility and "roll-back-ability" of the corresponding pipelinerun.
      default: ""
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: rebuild-nativelink-run-
      spec:
        pipelineRef:
          name: rebuild-nativelink
        workspaces:
          - name: optional-src
            persistentVolumeClaim:
              claimName: local-sources-pvc
          - name: nix-store
            persistentVolumeClaim:
              claimName: nix-store-pvc
        params:
          - name: flakeOutput
            value: "$(tt.params.flakeOutput)"
          - name: imageNameOverride
            value: "$(tt.params.imageNameOverride)"
          - name: imageTagOverride
            value: "$(tt.params.imageTagOverride)"
          - name: registry
            value: "kind-registry:5000"
          - name: insecureDisableTlsVerify
            value: "true"
          - name: enableNixSandbox
            value: "false"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: nativelink-rebuild-tb
spec:
  params:
    - name: flakeOutput
      value: "$(body.flakeOutput)"
    - name: imageNameOverride
      value: "$(body.imageNameOverride)"
    - name: imageTagOverride
      value: "$(body.imageTagOverride)"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-robot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-eventlistener-binding
subjects:
  - kind: ServiceAccount
    name: tekton-robot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-eventlistener-clusterbinding
subjects:
  - kind: ServiceAccount
    name: tekton-robot
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: eventlistener
spec:
  gatewayClassName: cilium
  listeners:
    - name: eventlistener
      protocol: HTTP
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: eventlistener-route
spec:
  parentRefs:
    - sectionName: eventlistener
      name: eventlistener
  rules:
    - backendRefs:
        # This name is generated by the the EventListener config below.
        - name: el-nativelink-rebuild
          port: 8080
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: nativelink-rebuild
spec:
  serviceAccountName: tekton-robot
  triggers:
    - name: nativelink-rebuild-trigger
      bindings:
        - ref: nativelink-rebuild-tb
      template:
        ref: nativelink-rebuild-tt
