[package]
name = "nativelink-scheduler"
version = "0.4.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-proto = { path = "../nativelink-proto" }
nativelink-metric = { path = "../nativelink-metric" }

# TODO(aaronmondal): This should not be a dependency. Move the corresponding
#                    files somewhere else.
nativelink-store = { path = "../nativelink-store" }

async-lock = "3.4.0"
async-trait = "0.1.81"
prost = "0.13.1"
uuid = { version = "1.10.0", features = ["v4"] }
futures = "0.3.30"
lru = "0.12.3"
mock_instant = "0.3.2"
parking_lot = "0.12.2"
rand = "0.8.5"
scopeguard = "1.2.0"
tokio = { version = "1.38.0", features = ["sync", "rt", "parking_lot"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tonic = { version = "0.12.0", features = ["gzip", "tls"] }
tracing = "0.1.40"
static_assertions = "1.1.0"

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }

pretty_assertions = "1.4.0"
