[package]
name = "nativelink-scheduler"
version = "0.4.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-proto = { path = "../nativelink-proto" }

# TODO(aaronmondal): This should not be a dependency. Move the corresponding
#                    files somewhere else.
nativelink-store = { path = "../nativelink-store" }

async-lock = "3.4.0"
async-trait = "0.1.81"
blake3 = "1.5.2"
prost = "0.13.1"
uuid = { version = "1.10.0", features = ["v4"] }
futures = "0.3.30"
hashbrown = "0.14"
lru = "0.12.3"
parking_lot = "0.12.3"
rand = "0.8.5"
scopeguard = "1.2.0"
tokio = { version = "1.38.0", features = ["sync", "rt", "parking_lot"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tonic = { version = "0.12.0", features = ["gzip", "tls"] }
tracing = "0.1.40"
bitflags = "2.6.0"
redis = { version = "0.25.4", features = ["aio", "tokio", "json"] }
serde = "1.0.204"
redis-macros = "0.3.0"
serde_json = "1.0.120"

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }

pretty_assertions = "1.4.0"
