---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nativelink
  namespace: default
spec:
  interval: 2m
  url: https://github.com/TraceMachina/nativelink
  ref:
    branch: main
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: nativelink-webhook
  namespace: flux-system
spec:
  type: generic
  address: http://el-nativelink-rebuild.default.svc.cluster.local:8080
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: nativelink-image-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: default
  providerRef:
    name: nativelink-webhook
  eventMetadata:
    flakeOutput: github:TraceMachina/nativelink#image
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: nativelink-worker-init-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: default
  providerRef:
    name: nativelink-webhook
  eventMetadata:
    flakeOutput: github:TraceMachina/nativelink#nativelink-worker-init
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: nativelink-worker-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: default
  providerRef:
    name: nativelink-webhook
  eventMetadata:
    flakeOutput: "PLACEHOLDER_NATIVELINK_WORKER"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nativelink-configmaps
  namespace: default
spec:
  interval: 2m
  path: "./kubernetes/configmaps"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: default
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nativelink
  namespace: default
spec:
  interval: 2m
  path: "PLACEHOLDER_NATIVELINK_KUSTOMIZATION"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: default
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: nativelink-image-tags
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: not-used
        spec:
          template:
            metadata:
              annotations:
                sidecar.opentelemetry.io/inject: "true"
      target:
        kind: Deployment
        labelSelector: "app.kubernetes.io/part-of=nativelink"
  dependsOn:
    - name: nativelink-configmaps
    - name: nativelink-tekton-resources
    - name: opentelemetry-collector
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nativelink-tekton-resources
  namespace: default
spec:
  interval: 2m
  path: "./kubernetes/components/tekton-resources"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: default
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 2m
  path: "./kubernetes/components/cert-manager"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: cert-manager
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nats
  namespace: flux-system
spec:
  interval: 2m
  path: "./kubernetes/components/nats"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: nats-system
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nats-kafka
  namespace: nats-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
  path: ./kubernetes/components/nats-kafka
  dependsOn:
    - name: nats
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry-operator
  namespace: flux-system
spec:
  interval: 2m
  path: "./kubernetes/components/opentelemetry-operator"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: opentelemetry-operator-system
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
  dependsOn:
    - name: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opentelemetry-collector
  namespace: default
spec:
  interval: 2m
  path: "./kubernetes/components/opentelemetry-collector"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: default
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
  dependsOn:
    - name: opentelemetry-operator
      namespace: flux-system
    - name: nats
      namespace: flux-system
