[package]
name = "nativelink-macro"
version = "0.4.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# TODO(allada) We currently need to pin these to specific version.
# Some down-stream can't be upgraded just yet.
proc-macro2 = "=1.0.84"
quote = "=1.0.36"
syn = "=2.0.66"
