apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../kubernetes/components/operator

patches:
- patch: |-
    - op: replace
      path: /spec/path
      value: ./kubernetes/overlays/chromium
  target:
    kind: Kustomization
    name: nativelink
- patch: |-
    - op: replace
      path: /spec/eventMetadata/flakeOutput
      value: github:TraceMachina/nativelink#nativelink-worker-siso-chromium
  target:
    kind: Alert
    name: nativelink-worker-alert
