---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nativelink-to-nats
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: nativelink
  egress:
  - to:  # Allow access to Kafka
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nats-system
      podSelector:
        matchLabels:
          app: kafka
    ports:
    - protocol: TCP
      port: 9092
  - to:  # Allow access to NATS
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nats-system
      podSelector:
        matchLabels:
          app.kubernetes.io/name: nats
    ports:
    - protocol: TCP
      port: 4222
  - to:  # Allow DNS resolution
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  policyTypes: [Egress]
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: nativelink-opentelemetry-collector
  labels:
    app.kubernetes.io/part-of: nativelink
spec:
  mode: sidecar
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      debug:
        verbosity: detailed
      kafka:
        brokers: ["kafka.nats-system.svc.cluster.local:9092"]
        protocol_version: "2.0.0"
        encoding: "otlp_proto"
        topic: otel-telemetry
        metadata:
          full: true
        timeout: 5s
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    service:
      telemetry:
        metrics:
          address: "0.0.0.0:8888"
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, kafka]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus, debug, kafka]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, kafka]
