name: CI

# Controls when the workflow will run.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    # The type of runner that the job will run on.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Which OS versions we will test on.
        os_version: [ 20.04, 22.04 ]
    steps:
    - uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deployment-examples/docker-compose/Dockerfile
        build-args: |
          OPT_LEVEL=fastbuild
          OS_VERSION=${{ matrix.os_version }}
        target: builder-externals-built
        load: true # This brings the build into `docker images` from buildx.
        tags: allada/turbo-cache:test
        cache-from: type=gha,scope=main
        cache-to: type=gha,scope=main,mode=max

    - name: Bazel test
      run: docker run --rm -e CC=clang -v $PWD:/root/turbo-cache allada/turbo-cache:test bazel test //...
  integration-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Which OS versions we will test on.
        os_version: [ 20.04, 22.04 ]
    steps:
    - uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deployment-examples/docker-compose/Dockerfile
        build-args: |
          OPT_LEVEL=fastbuild
          OS_VERSION=${{ matrix.os_version }}
        # The `builder` stage is pointless to be cached because any change to the
        # PR invalidates it. So to save the limited cache space we skip it.
        no-cache-filters: |
          builder
        load: true # This brings the build into `docker images` from buildx.
        tags: allada/turbo-cache:latest
        cache-from: type=gha,scope=main
        cache-to: type=gha,scope=main,mode=max

    - name: Run tests
      run: ./run_integration_tests.sh

  asan-tests:
    # The type of runner that the job will run on.
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deployment-examples/docker-compose/Dockerfile
        build-args: |
          ADDITIONAL_BAZEL_FLAGS=--config=asan
        target: builder-externals-built
        load: true # This brings the build into `docker images` from buildx.
        tags: allada/turbo-cache:asan-test
        cache-from: type=gha,scope=main
        cache-to: type=gha,scope=main,mode=max

    - name: Bazel test
      run: |
        docker run \
          --rm \
          -e CC=clang \
          -v $PWD:/root/turbo-cache allada/turbo-cache:asan-test \
          bazel test \
            --config=asan \
            //...
