name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0
    - name: Cache bazel
      uses: actions/cache@v3.3.1
      env:
        cache-name: bazel-cache
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Bazel test
      run: bazel test //...
  integration-tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: ${{ runner.os }}-{hash}-v1
        restore-keys: |
          docker-compose-cache-

    - name: Run tests
      run: sudo ./run_integration_tests.sh
