---
name: Nix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  nix-bazel:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Mount Nix cache
        uses: actions/cache@v3.3.2
        with:
          key: ${{ runner.os }}-nix
          path: ~/nix
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-nix
      - name: Invoke Bazel build in Nix shell
        run: >
          nix --store ~/nix develop --impure --command
          bash -c "bazel test ..."
  nix-cargo:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Mount Nix cache
        uses: actions/cache@v3.3.2
        with:
          key: ${{ runner.os }}-nix
          path: ~/nix
      - name: Invoke Cargo build in Nix shell
        run: >
          nix --store ~/nix develop --impure --command
          bash -c "cargo test --all"
