---
name: Check pre-commit hooks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  pre-commit-checks:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: >- # v3.5.3
          actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Install Nix
        uses: >- # v9
          DeterminateSystems/nix-installer-action@cd46bde16ab981b0a7b2dce0574509104543276e
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-installer-tag: v0.16.1

      - name: Cache Nix derivations
        uses: >- # Custom commit, last pinned at 2024-03-03.
          DeterminateSystems/magic-nix-cache-action@742d8701e54851d2136f71b61d31382a4f4d0788

      - name: Run pre-commit hooks
        run: nix flake check
